import { Poppins } from "next/font/google";
import "@/styles/globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["100", "300", "500", "700", "900"],
  subsets: ["latin"],
  display: "optional",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body className="mx-auto mt-40 h-full max-w-[1400px] justify-center px-8 text-center sm:px-0">
        {children}
      </body>
    </html>
  );
}
